{% set version = "0.9.28" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tables
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tables_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tables/tables_{{ version }}.tar.gz
  sha256: ccd2cf3c490af14e424feda39ffc445d74cabc0c2c920765eab44b26515fb329

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmltools
    - r-knitr
  run:
    - r-base
    - r-htmltools
    - r-knitr

test:
  commands:
    - $R -e "library('tables')"           # [not win]
    - "\"%R%\" -e \"library('tables')\""  # [win]

about:
  home: https://r-forge.r-project.org/projects/tables/
  license: GPL-2.0-only
  summary: Computes and displays complex tables of summary statistics. Output may be in LaTeX, HTML, plain text, or an R matrix for further processing.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - izahn
    - conda-forge/r
